### ISSUE TITLE
3.2 Set Up Data Structures

### ISSUE THREAD

**Issue by Takosaga** [Takosaga/ai_group_project#11]
Deliverable: Data organized in the formats

**Comment by Takosaga** [comment]
This will be exported in PASCAL VOC 1.1 to [data/processed](https://github.com/Takosaga/ai_group_project/tree/main/data/processed) once data has been labeled

**Comment by dgizdevans** [comment]
As for the preparation of the data structure, preliminary test attempts to train the model indicated that more data (images) is needed for each stage: training, validation, and testing. Therefore, I am currently collecting data (images) from November 25th to November 28th. The final goal is a minimum of 1200 images to ensure there is enough data for model training.

**Comment by dgizdevans** [comment]
Created a process for preparing and distributing files for subsequent model training using Google Cloud Storage.

notebooks/data_sorter.ipynb

Prepared data for test model training and distributed in a 60/20/20 ratio across train, val, and test folders
