### ISSUE TITLE
5.1 Hyperparameter Tuning and Retraining

### ISSUE THREAD

**Issue by Takosaga** [Takosaga/ai_group_project#16]
Deliverable: Improved model performance via tuning

**Comment by Takosaga** [comment]
Will give additional 3-5% , 
now we have 0.88 average precision , we can get 0.93 with retraining

5-6 hours to be done

**Comment by dgizdevans** [comment]
Added a notebook for working with augmented data (`yolov8_augmented_model_training_and_evaluation.ipynb`). 

While the expectations were not fully met, here are the results from one cycle of augmentation:

- **Confidence Improvement**: 
  - Average Confidence increased across all test sets by approximately 2.2% to 2.3%.
  - Median Confidence improved by around 2.0% to 2.2%, indicating a consistent upward shift in confidence levels.
  
- **Reduced Variability**:
  - Standard Deviation decreased by 5.5% to 6.5%, reflecting more stable and consistent predictions by the augmented model.
  
- **Overall Trends**:
  - All test sets showed a consistent pattern of improvement, suggesting the augmentation benefits are generalizable across different unlabeled datasets.
