### ISSUE TITLE
1a. Research which base-line models to use

### ISSUE THREAD

**Issue by Takosaga** [Takosaga/ai_group_project#3]
Which 3 base-line models should we use?

**Comment by Takosaga** [comment]
[Survey of object detection models](https://doi.org/10.1016/j.dsp.2022.103514)
[Review of vehicle detection methods](https://doi.org/10.26599/jicv.2023.9210019)

**Comment by Takosaga** [comment]
Models for real-time dection that have a paper and license is open to use

More helpful online resources 
[Top object Detection Models](https://youtu.be/dL9B9VUHkgQ?si=NdaJJQnSX8jeCP2s)
[Leaderboard trained on COCO 2017](https://leaderboard.roboflow.com/)

**Comment by Takosaga** [comment]
Post by the end of Thursday about your research
Requirments:
- [ ]  Used for real-time detection
- [ ]  Research based
- [ ]  Open License

Things to consider:
-  ease to implement
-  size
-  training time

**Comment by Takosaga** [comment]
<details> 
  <summary> My research, may be different from what yall found so have as spoiler. </summary>
   
Most of my research comes from here [Review of vehicle detection methods](https://doi.org/10.26599/jicv.2023.9210019)

   I made the mistake that algorithms that detect as the model where these are some of the names of the [base line models](https://ieeexplore.ieee.org/mediastore/IEEE/content/media/9944931/10520218/10520219/JICV0019-table-1-source-large.gif)

   Though if you look are this [table](https://ieeexplore.ieee.org/mediastore/IEEE/content/media/9944931/10520218/10520219/JICV0019-table-2-source-large.gif)

   I would propose using Darknet, ResNet101, VGG-16 (though may take long to train)

   From second [Survey of object detection models](https://doi.org/10.1016/j.dsp.2022.103514) is this base comparision named as [backbone](https://i.postimg.cc/qvkVxM2M/table-from-survey.png)
</details>

**Comment by dgizdevans** [comment]
here is my research for this topic : https://docs.google.com/document/d/16TzqiEIuyZycxaXzS04VfS_whHS0G_VJ_Es68DMjA3M/edit?usp=sharing

**Comment by Takosaga** [comment]
Looking at @dgizdevans research. 

The detection algorithms YOLOv5, SSD MobileNet, and Faster R-CNN
YOLOv5 using [CSPDarknet](https://huggingface.co/docs/timm/models/csp-darknet)
SSD MobileNet using MobileNet, though [MoblileNet v2](https://huggingface.co/docs/timm/models/mobilenet-v2) and [MobileNet v3](https://huggingface.co/docs/timm/models/mobilenet-v3)
Faster R-CNN using [ResNet](https://huggingface.co/docs/timm/models/resnet) or VGG
Along with [EfficientNet](https://huggingface.co/docs/timm/models/efficientnet) and RetinaNet

The libary [timm](https://huggingface.co/docs/timm/index) has it able to train many pretrained models, so may be choice to go on that.

**Comment by Takosaga** [comment]
Models Chosen:
- CSPDarknet
- MobileNet
- ResNet

Backup Model
- EfficientNet
