### ISSUE TITLE
1.b Which camera feeds will be used

### ISSUE THREAD

**Issue by Takosaga** [Takosaga/ai_group_project#4]
Which camera feeds will be used? What criteria should it meet?

**Comment by Takosaga** [comment]
Possible Cameras
[Vanšu tilts](https://balticlivecam.com/cameras/latvia/riga/vansu-bridge/)
[Rīgas Centrāltirgus](http://www.eradio.lv/kameras/tirgus.php)
[Akmens tilts](https://www.lsm.lv/tiesraides-kameras/lnb-eka/)

Possible Requirements
[General Requirements](https://docs.google.com/document/d/1ihN2gd3Wvj_mN9rSmHzeqfsQHcyGAvG5CuDCqeVjem8/edit?tab=t.0)

**Comment by dgizdevans** [comment]
"An initial inspection showed that all cameras (broadcasts) at dusk and in darkness have very poor quality, which will not allow for determining vehicle types. At best, only the total number of vehicles can be counted.

The camera for the cable-stayed bridge near the Islande Hotel is too far away and low in quality.

The camera for the Stone Bridge is much better, even in low light."

**Comment by Takosaga** [comment]
Yeah, we will need to decide only one camera view, multiple or even if we are going to focus on the bridge. The proposal technically didn't have we were only tracking at bridge, though would be nice since it is a concern for traffic.

**Comment by Takosaga** [comment]
Depending on video quality during image capture, these will be possible cameras:

[Vanšu tilts](https://balticlivecam.com/cameras/latvia/riga/vansu-bridge/)
[Akmens tilts](https://www.lsm.lv/tiesraides-kameras/lnb-eka/)
[Rīgas Centrāltirgus](http://www.eradio.lv/kameras/tirgus.php)
With one more as backup
