### ISSUE TITLE
2.1 Collect Sample Data

### ISSUE THREAD

**Issue by Takosaga** [Takosaga/ai_group_project#8]
Deliverable: Initial sample vehicle dataset (videos/images) from the webcams according to 1.b

**Comment by Takosaga** [comment]
Raw data will be placed in folders named after us [here](https://github.com/Takosaga/ai_group_project/tree/main/data/raw) for us to label

**Comment by dgizdevans** [comment]
Data collected. Divided into three equal parts and placed in a folder : /data/raw
